### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by asivaneswaran** [GoogleWebComponents/google-analytics#30]
Hi,

The demo is not working:
http://googlewebcomponents.github.io/google-analytics/components/google-analytics/demo/

It asks for the right account and property but no data is shown.

**Comment by philipwalton** [comment]
The new location for the demo is here:
https://elements.polymer-project.org/elements/google-analytics?view=demo:demo/index.html&active=google-analytics-chart

We'll work on updating all old links.
