### ISSUE TITLE
Server Side Authorization

### ISSUE THREAD

**Issue by punteney** [GoogleWebComponents/google-analytics#35]
Is there anyway to do server side authorization for the components? Much like this example
https://ga-dev-tools.appspot.com/embed-api/server-side-authorization/, but using the polymer components instead of the embed API?

Thanks

**Comment by philipwalton** [comment]
I don't believe there is, but either way it would be done via the [`<google-signin>`](https://github.com/googlewebcomponents/google-signin) component. I'd recommend asking on that repo and/or suggesting it as a feature.
