### ISSUE TITLE
Demo on Polymer not working

### ISSUE THREAD

**Issue by LoveAndHappiness** [GoogleWebComponents/google-analytics#36]
https://elements.polymer-project.org/elements/google-analytics?view=demo

**Comment by ebidel** [comment]
@philipwalton I think that element the query element needs `@demo` at the top.

It's the only one that doesn't render the demo link. 

@LoveAndHappiness The full demo is here:
https://elements.polymer-project.org/elements/google-analytics?view=demo:demo/index.html&active=google-analytics-view-selector

Try switching to a different element in the Bundled elements section
