### ISSUE TITLE
Where is file ../../webcomponentsjs/webcomponents-lite.js?

### ISSUE THREAD

**Issue by partyzant** [GoogleWebComponents/google-analytics#40]
Where do I got to get this file from? There is no such file in this repository.

**Comment by ebidel** [comment]
It's a dependency of polymer. When you `bower install GoogleWebComponents/google-analytics`, it will be installed in` bower_components/webcomponentsjs/webcomponents-lite.js`

**Comment by partyzant** [comment]
Then how to install it and why there is nothing about how to do it in documentation?

**Comment by ebidel** [comment]
https://www.polymer-project.org/1.0/docs/start/getting-the-code.html#using-bower

This is how bower works. bower.json lists a component's dependencies and those get pulled down as sibling folders. The docs show the bower install command.
