### ISSUE TITLE
This week vs. Last Week View using google-analytics-chart

### ISSUE THREAD

**Issue by bigkpi** [GoogleWebComponents/google-analytics#42]
Hello, 

I am trying to plot this week vs. last week line graph using google-analytics-chart (using polymer)- just like https://ga-dev-tools.appspot.com/embed-api/third-party-visualizations/ (however using google-analytics-chart instead of chart.js). 

Is it possible to do without writing custom component? Is there such example I can follow? Thank you again for your help. If not can I request such feature? thank you.

**Comment by ebidel** [comment]
google-analytics-date-selector would work for this. There's an example in the docs: https://elements.polymer-project.org/elements/google-analytics?active=google-analytics-date-selector

**Comment by bigkpi** [comment]
Thank you for your reply. The method you suggest creates two chart. I am trying to combine them into a single chart like the way chart.js does. I must be missing something simple? Is it possible?

**Comment by ebidel** [comment]
Then you'd have to write this yourself. There are a few elements that you can compose together that would accomplish what you want. https://elements.polymer-project.org/elements/google-analytics?active=google-analytics-query for example takes a start/end date. You could feed that into any charting solution you want.

**Comment by bigkpi** [comment]
For one reason or another I am not making progress. I am not sure how do I get the result out of google-analytics-query let alone send the data to google-analytlics-chart. My query now looks like 

<google-analytics-query
  data="{{myVariable}}"
  ids="ga:123"
  metrics="ga:sessions"
  output="dataTable"
  dimensions="ga:country">
</google-analytics-query>

How do I access myVariable? or output? are there examples where those properties are being used to see how query pass data to chart? Great if you can provide a simple example for me to follow. thanks.
